// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/HeyReyHR/rocket-factory/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// InventoryService is an autogenerated mock type for the InventoryService type
type InventoryService struct {
	mock.Mock
}

type InventoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryService) EXPECT() *InventoryService_Expecter {
	return &InventoryService_Expecter{mock: &_m.Mock}
}

// Part provides a mock function with given fields: ctx, uuid
func (_m *InventoryService) Part(ctx context.Context, uuid string) (model.Part, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Part")
	}

	var r0 model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Part, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Part); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Part)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_Part_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Part'
type InventoryService_Part_Call struct {
	*mock.Call
}

// Part is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *InventoryService_Expecter) Part(ctx interface{}, uuid interface{}) *InventoryService_Part_Call {
	return &InventoryService_Part_Call{Call: _e.mock.On("Part", ctx, uuid)}
}

func (_c *InventoryService_Part_Call) Run(run func(ctx context.Context, uuid string)) *InventoryService_Part_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InventoryService_Part_Call) Return(_a0 model.Part, _a1 error) *InventoryService_Part_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_Part_Call) RunAndReturn(run func(context.Context, string) (model.Part, error)) *InventoryService_Part_Call {
	_c.Call.Return(run)
	return _c
}

// Parts provides a mock function with given fields: ctx, filter
func (_m *InventoryService) Parts(ctx context.Context, filter model.Filter) ([]model.Part, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Parts")
	}

	var r0 []model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Filter) ([]model.Part, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Filter) []model.Part); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Filter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_Parts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parts'
type InventoryService_Parts_Call struct {
	*mock.Call
}

// Parts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.Filter
func (_e *InventoryService_Expecter) Parts(ctx interface{}, filter interface{}) *InventoryService_Parts_Call {
	return &InventoryService_Parts_Call{Call: _e.mock.On("Parts", ctx, filter)}
}

func (_c *InventoryService_Parts_Call) Run(run func(ctx context.Context, filter model.Filter)) *InventoryService_Parts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Filter))
	})
	return _c
}

func (_c *InventoryService_Parts_Call) Return(_a0 []model.Part, _a1 error) *InventoryService_Parts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_Parts_Call) RunAndReturn(run func(context.Context, model.Filter) ([]model.Part, error)) *InventoryService_Parts_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryService creates a new instance of InventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryService {
	mock := &InventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
